seed: 42

# Models are instantiated using skrl's model instantiator utility
models:
  separate: False
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [256, 256, 128]  # Larger network for combined base+arm control
        activations: elu
    output: ACTIONS
  value:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [256, 256, 128]  # Matching policy network size
        activations: elu
    output: ONE

# Rollout memory
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)

# PPO agent configuration
agent:
  class: PPO
  rollouts: 24  # Collect good amount of experience per iteration
  learning_epochs: 5
  mini_batches: 4
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 3.0e-04
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.01  # Encourage exploration
  value_loss_scale: 2.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: "franka_mobile_reach"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto

# Sequential trainer
trainer:
  class: SequentialTrainer
  timesteps: 24000  # Train longer for more complex task
  environment_info: log